@file:Suppress("UnstableApiUsage")

package dev.slne.surf.event.collectit.utils

import dev.slne.surf.surfapi.core.api.util.objectSetOf
import org.bukkit.inventory.ItemType

val EXCLUDED_ITEMS = objectSetOf(
    // --- Core unobtainable blocks ---
    ItemType.AIR,
    ItemType.BARRIER,
    ItemType.BEDROCK,
    ItemType.BUDDING_AMETHYST,
    ItemType.CHORUS_PLANT,
    ItemType.COMMAND_BLOCK,
    ItemType.CHAIN_COMMAND_BLOCK,
    ItemType.REPEATING_COMMAND_BLOCK,
    ItemType.COMMAND_BLOCK_MINECART,
    ItemType.DEBUG_STICK,
    ItemType.DIRT_PATH,
    ItemType.END_PORTAL_FRAME,
    ItemType.FARMLAND,
    ItemType.JIGSAW,
    ItemType.KNOWLEDGE_BOOK,
    ItemType.LIGHT,
    ItemType.PETRIFIED_OAK_SLAB,
    ItemType.PLAYER_HEAD,
    ItemType.REINFORCED_DEEPSLATE,
    ItemType.SPAWNER,
    ItemType.STRUCTURE_BLOCK,
    ItemType.STRUCTURE_VOID,
    ItemType.TEST_BLOCK,
    ItemType.TEST_INSTANCE_BLOCK,
    ItemType.VAULT,

    // --- Suspicious blocks ---
    ItemType.SUSPICIOUS_SAND,
    ItemType.SUSPICIOUS_GRAVEL,

    // --- Frogspawn etc. ---
    ItemType.FROGSPAWN,

    // --- Trial spawner ---
    ItemType.TRIAL_SPAWNER,

    // --- Infested blocks ---
    ItemType.INFESTED_STONE,
    ItemType.INFESTED_COBBLESTONE,
    ItemType.INFESTED_STONE_BRICKS,
    ItemType.INFESTED_MOSSY_STONE_BRICKS,
    ItemType.INFESTED_CRACKED_STONE_BRICKS,
    ItemType.INFESTED_CHISELED_STONE_BRICKS,
    ItemType.INFESTED_DEEPSLATE,

    // --- Spawn eggs ---
    ItemType.ALLAY_SPAWN_EGG,
    ItemType.ARMADILLO_SPAWN_EGG,
    ItemType.AXOLOTL_SPAWN_EGG,
    ItemType.BAT_SPAWN_EGG,
    ItemType.BEE_SPAWN_EGG,
    ItemType.BLAZE_SPAWN_EGG,
    ItemType.BOGGED_SPAWN_EGG,
    ItemType.BREEZE_SPAWN_EGG,
    ItemType.CAMEL_SPAWN_EGG,
    ItemType.CAT_SPAWN_EGG,
    ItemType.CAVE_SPIDER_SPAWN_EGG,
    ItemType.CHICKEN_SPAWN_EGG,
    ItemType.COD_SPAWN_EGG,
    ItemType.COPPER_GOLEM_SPAWN_EGG,
    ItemType.COW_SPAWN_EGG,
    ItemType.CREAKING_SPAWN_EGG,
    ItemType.CREEPER_SPAWN_EGG,
    ItemType.DOLPHIN_SPAWN_EGG,
    ItemType.DONKEY_SPAWN_EGG,
    ItemType.DROWNED_SPAWN_EGG,
    ItemType.ELDER_GUARDIAN_SPAWN_EGG,
    ItemType.ENDER_DRAGON_SPAWN_EGG,
    ItemType.ENDERMAN_SPAWN_EGG,
    ItemType.ENDERMITE_SPAWN_EGG,
    ItemType.EVOKER_SPAWN_EGG,
    ItemType.FOX_SPAWN_EGG,
    ItemType.FROG_SPAWN_EGG,
    ItemType.GHAST_SPAWN_EGG,
    ItemType.GLOW_SQUID_SPAWN_EGG,
    ItemType.GOAT_SPAWN_EGG,
    ItemType.GUARDIAN_SPAWN_EGG,
    ItemType.HAPPY_GHAST_SPAWN_EGG,
    ItemType.HOGLIN_SPAWN_EGG,
    ItemType.HORSE_SPAWN_EGG,
    ItemType.HUSK_SPAWN_EGG,
    ItemType.IRON_GOLEM_SPAWN_EGG,
    ItemType.LLAMA_SPAWN_EGG,
    ItemType.MAGMA_CUBE_SPAWN_EGG,
    ItemType.MOOSHROOM_SPAWN_EGG,
    ItemType.MULE_SPAWN_EGG,
    ItemType.OCELOT_SPAWN_EGG,
    ItemType.PANDA_SPAWN_EGG,
    ItemType.PARROT_SPAWN_EGG,
    ItemType.PHANTOM_SPAWN_EGG,
    ItemType.PIG_SPAWN_EGG,
    ItemType.PIGLIN_SPAWN_EGG,
    ItemType.PIGLIN_BRUTE_SPAWN_EGG,
    ItemType.PILLAGER_SPAWN_EGG,
    ItemType.POLAR_BEAR_SPAWN_EGG,
    ItemType.PUFFERFISH_SPAWN_EGG,
    ItemType.RABBIT_SPAWN_EGG,
    ItemType.RAVAGER_SPAWN_EGG,
    ItemType.SALMON_SPAWN_EGG,
    ItemType.SHEEP_SPAWN_EGG,
    ItemType.SHULKER_SPAWN_EGG,
    ItemType.SILVERFISH_SPAWN_EGG,
    ItemType.SKELETON_SPAWN_EGG,
    ItemType.SKELETON_HORSE_SPAWN_EGG,
    ItemType.SLIME_SPAWN_EGG,
    ItemType.SNIFFER_SPAWN_EGG,
    ItemType.SNOW_GOLEM_SPAWN_EGG,
    ItemType.SPIDER_SPAWN_EGG,
    ItemType.SQUID_SPAWN_EGG,
    ItemType.STRAY_SPAWN_EGG,
    ItemType.STRIDER_SPAWN_EGG,
    ItemType.TADPOLE_SPAWN_EGG,
    ItemType.TRADER_LLAMA_SPAWN_EGG,
    ItemType.TROPICAL_FISH_SPAWN_EGG,
    ItemType.TURTLE_SPAWN_EGG,
    ItemType.VEX_SPAWN_EGG,
    ItemType.VILLAGER_SPAWN_EGG,
    ItemType.VINDICATOR_SPAWN_EGG,
    ItemType.WANDERING_TRADER_SPAWN_EGG,
    ItemType.WARDEN_SPAWN_EGG,
    ItemType.WITCH_SPAWN_EGG,
    ItemType.WITHER_SPAWN_EGG,
    ItemType.WITHER_SKELETON_SPAWN_EGG,
    ItemType.WOLF_SPAWN_EGG,
    ItemType.ZOGLIN_SPAWN_EGG,
    ItemType.ZOMBIE_SPAWN_EGG,
    ItemType.ZOMBIE_HORSE_SPAWN_EGG,
    ItemType.ZOMBIE_VILLAGER_SPAWN_EGG,
    ItemType.ZOMBIFIED_PIGLIN_SPAWN_EGG
)